version: '3.8'

services:
  backend:
    container_name: sceneStream_backend
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./back_end/.env
    volumes:
      - ./back_end:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped