version: '3.8'

services:
  backend:
    container_name: sceneStream_backend
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./back_end/.env
    volumes:
      - ./back_end:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend_dev:
    container_name: sceneStream_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge